apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-csi-driver.fullname" . }}-hcloud-csi-node-metrics
  labels:
    app: hcloud-csi
  {{- include "hcloud-csi-driver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hcloudCsiNodeMetrics.type }}
  selector:
    app: hcloud-csi
  {{- include "hcloud-csi-driver.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.hcloudCsiNodeMetrics.ports | toYaml | nindent 2 -}}