apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-csi-driver.fullname" . }}-hcloud-csi-controller-metrics
  labels:
    app: hcloud-csi-controller
  {{- include "hcloud-csi-driver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hcloudCsiControllerMetrics.type }}
  selector:
    app: hcloud-csi-controller
  {{- include "hcloud-csi-driver.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.hcloudCsiControllerMetrics.ports | toYaml | nindent 2 -}}