apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcloud-csi-driver.fullname" . }}-hcloud-csi-controller
  labels:
  {{- include "hcloud-csi-driver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.hcloudCsiController.serviceAccount.annotations | nindent 4 }}