
{{ if .Values.rbac.create -}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crontab.serviceAccountName" . }}
  labels:
    {{- include "crontab.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "exec"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crontab.serviceAccountName" . }}
  labels:
    {{- include "crontab.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "crontab.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crontab.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{ end }}
